# -*- coding: utf-8 -*-
"""try_catch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrdJdi1RaQb6NeXTb_QpnRWUsBKlXQKG
"""

#try catch
file_name = input("Enter the file name you are looking for: ")

# Try block
try:
  with open(file_name, 'r') as f:
      content = f.read()
      # Enter search term
      search_term = input("Enter a search term: ")
      # If term is not in file
      if search_term not in content:
          print(f"Search term '{search_term}' not found in file '{file_name}'.")
      # If term is in file
      else:
          print(f"Search term '{search_term}' found in file '{file_name}'.")

# Except blocks
except FileNotFoundError:
  print(f"File '{file_name}' not found.")
except IsADirectoryError:
  print(f"'{file_name}' is a directory, not a file.")
except Exception as e:
  print(f"An error occurred: {str(e)}")